### ISSUE TITLE
Methods for accessing node's siblings

### ISSUE THREAD

**Issue by VincTheSecond** [udapi/udapi-python#11]
Implement a set of new methods for accessing node's siblings.

**Comment by martinpopel** [comment]
`node.parent.children` is just 7 characters longer than `node.siblings`.
Is there any other reason, why we need the siblings method?
E.g. `node.siblings(following_only=True)`?

**Comment by VincTheSecond** [comment]
So far, no reason, just to offer method/property which will be used often.
Maybe later we define some other features of such method/property.

**Comment by martinpopel** [comment]
OK, closing for now. We can reopen the issue once needed.
