### ISSUE TITLE
Make readConllu to be more robust

### ISSUE THREAD

**Issue by VincTheSecond** [udapi/udapi-python#13]
An exception in the set_parent() "kills" the all reading process and the whole scenario.
I propose to reuse the `strict` flag. If true, the reading will terminate on such exceptions. Otherwise it just log warning and will continue to the next bundle.

**Comment by martinpopel** [comment]
The [exception](https://github.com/udapi/udapi-python/blob/master/udapi/core/node.py#L93) is there so the dependencies do not contain a cycle. A cycle in the data is a critical error, which cannot be ignored, so I think the exception should stay there.

Is there a real use case when we have invalid CoNLL-U data with cycles (in the basic dependencies) and we want to read at least the valid bundles? If yes, the exception should be caught [in the reader](https://github.com/udapi/udapi-python/blob/master/udapi/block/read/conllu.py#L191) and make sure it does not slow down loading of valid files. If not, let's close this issue for now.

**Comment by VincTheSecond** [comment]
The described issue have happen during the CzEng processing.
I think, I implemented the solution as you propose, see the pull request #14
