### ISSUE TITLE
Bugs in CoNLLU roundtrip

### ISSUE THREAD

**Issue by martinpopel** [udapi/udapi-python#24]
[Tests](https://travis-ci.org/udapi/udapi-python/builds/184547438) fail.

**Comment by VincTheSecond** [comment]
For Python 3+ there is still a problem when trying to write data to the STDOUT.
To pass the tests, I modified the `external_tests.sh` such that the output is written to the file.

After 2 hours of tests and googling, I'm still not able to fix writing to the STDOUT in Python 3+ :-(
