### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by danielhers** [udapi/udapi-python#42]
Can udapi-python be uploaded to [PyPI](https://pypi.python.org/) so it will be installable by `pip install udapi-python`?
Technically it's very simple (and I don't mind doing it myself if I you want) - create a PyPI account and then

    pip install twine
    python setup.py bdist_wheel sdist
    twine upload dist/*

**Comment by martinpopel** [comment]
Thanks for pushing this. I will upload it to PyPI soon, I hope.
I need to choose a licence first and also reconsider, if the name should be `udapi-python` or just `udapi`.

**Comment by danielhers** [comment]
Thanks. I vote for just `udapi` :)

**Comment by martinpopel** [comment]
Done. See https://pypi.python.org/pypi/udapi

**Comment by danielhers** [comment]
Thanks!
