### ISSUE TITLE
punctuation in flat:name

### ISSUE THREAD

**Issue by gossebouma** [udapi/udapi-python#45]
When converting Dutch data to UD I rely on udapy -s FixPunct to re-attach punctuation (as the original treebank attaches everything to root).
A problem arises in cases where punctuation is part of a proper name, as in 

mr. M.J.E.M. ( Michel ) Jager

Here the original annotators have included the paired brackets as part of the name. 
I am not sure this is according to UD guidelines, but during automatic conversion I cannot do much about this and simply have to label these elements with flat:name.
FixPunct however recognizes these as paired brackets (I think) and re-attaches them, which then causes problems with downstream validation (ie a flat:name relation pointing in the wrong direction).
The problem persists even if I re-assign a POS label SYM to these (my hack to try to avoid FixPunct from interfering). 
I had a look  at the code but did not see where to make modifications exactly. One conservative way out it seems (that would help me for now) is to restrict re-attachment of paired brackets to nodes that actually have POS=PUNCT. 
Any other suggestions for how to fix this (other than re-annotating the sources, which I will not) appreciated as well.

**Comment by martinpopel** [comment]
For *subordinate punctuation*, `FixPunct` touches only nodes with upos=PUNCT. However, for *paired punctuation* the code ignored upos and just checked the `PAIRED_PUNCT` list of word forms. I still think this makes sense, so I kept the default behavior as it was, but in #46 I added a `check_paired_punct_upos` parameter, which hopefully does what you asked for. Please try it (`git fetch origin; git checkout -b fix45-punct origin/fix45-punct; udapy -s ud.FixPunct check_paired_punct_upos=1 < in > out`) and let me know if I can merge it to the master. I am busy now to test it properly myself.

The reason why I prefer the default `check_paired_punct_upos=False` is that I have seen many treebanks where paired punctuation was not marked with upos=PUNCT. Applying `ud.FixPunct` does not really fix it as it never changes any upos, but it makes the error visible (there is a test that deprel=`punct` implies upos=PUNCT) and easy to fix.

I am keeping aside the question what should be the proper annotation of "mr. M.J.E.M. ( Michel ) Jager" according to the guidelines. This should be perhaps discussed at https://github.com/universaldependencies/docs/issues unless it is obvious from the guidelines. My opinion: it is still a clear bracket, so it should have upos=PUNCT (it is not a word-like entity, so it should not be SYM). Thus according to [svalidation](http://universaldependencies.org/svalidation.html#punct-is-attached-as-neither-punct-nor-root) it should have deprel=`punct`. Of course, you could argue that test is wrong and it should allow `flat:name` in addition to `punct` and `root`.  The [corresponding test](https://github.com/udapi/udapi-python/blob/9d8365ecdb02dece78aaea8de942e9dd750d346e/udapi/block/ud/markbugs.py#L168) in `ud.MarkBugs` allows also `goeswith` and `fixed`.

Note that you can apply [ud.FixRightheaded](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/fixrightheaded.py) after `ud.FixPunct` to fix the `flat:name`.

**Comment by gossebouma** [comment]
Yes, the check_paired_punct_upos=1 works fine for me.

Thanks! 

(The issue with punctuation in names in general seems hard to resolve, I have noted that various versions of the underlying treebank annotation also differ in how they treat these.)
