### ISSUE TITLE
FixPunct in enhanced deps

### ISSUE THREAD

**Issue by gossebouma** [udapi/udapi-python#47]
I rely on  udapy -s ud.FixPunct to re-attach punctuation according to ud guidelines.This script does not fix attachment in enhanced deps, however. It is not very complicated to remedy this (ie simply copy the modified attachment targets to the enhanced deps field) but it might be nice to include this in the script. Or is there some flag I am missing? 
I don't think there is ever anything that affects punctuation in enhanced, so this should be safe.

**Comment by martinpopel** [comment]
Good idea to include enhanced deps as well. Either send a PR or wait until I'll get to it.

**Comment by martinpopel** [comment]
Sorry it took me so long to add 4 lines of code.
I thought it will be more complicated (traversing the enhanced deps with multiple parents and empty nodes), but if we think that for PUNCT node the enhanced deps should always follow the basic deps, then the copying is really easy (it overwrites whatever was in enh deps for PUNCT nodes, but I guess that's ok).
