### ISSUE TITLE
Using the UDAPI-python within a Python code

### ISSUE THREAD

**Issue by bperak** [udapi/udapi-python#50]
Dear admins of the UDAPI
Is there a clear documentation how to use the UDAPI from within a code, as a part of the Python code?
I am trying to include the UDAPI function to parse a text and then to get the result within a custom Python programme.
Thank you
Benedikt

**Comment by martinpopel** [comment]
[test_node.py](https://github.com/udapi/udapi-python/blob/master/udapi/core/tests/test_node.py) shows some examples how to use Udapi from Python, but I usually it is less work to the CLI `udapy`. You can do it the other way round: write a Udapi block which will wrap your custom Python programme.

Udapi can integrate various taggers and parsers, but currently only [UDPipe](http://ufal.mff.cuni.cz/udpipe) is integrated. If you want use Udapi just for tagging+parsing, you can use UDPipe directly - it has a Python interface and much better documentation than Udapi. (There is also an option to load the parsed CoNLL-U files in your custom Python programme without using any Python API.)
