### ISSUE TITLE
Why: -= 0

### ISSUE THREAD

**Issue by pebbe** [udapi/udapi-python#55]
Why is this?
```python
    if nested_level > 0:
        nested_level -= 0
```
I would expect: -= 1

https://github.com/udapi/udapi-python/blob/5b582f6b9a1a705767222c9b628ed4dbfd10186b/udapi/block/ud/fixpunct.py#L201

**Comment by martinpopel** [comment]
Thanks for catching this bug! Yes, it was broken from the begging, over two years.
(I had a sentence with nested quotes where the inner quotation was correct, but I should have included also an incorrect inner quotation in my test suite.)
