### ISSUE TITLE
problem with the read.Conllu block and filelists

### ISSUE THREAD

**Issue by francescomambrini** [udapi/udapi-python#56]
Hi,
I am trying to apply blocks to a bunch of .conllu files and I'd like to read them from a filelist. When I try:
```bash
udapy read.Conllu files=@inputlist.txt my.Block
```
it fails with the error message (end of the stack):
```python
File "[...]/udapi-python/udapi/core/files.py", line 117, in next_filehandle
    filename_extension = filename.split('.')[-1]
AttributeError: 'list' object has no attribute 'split'
```   
Indeed, it seems that the problem is the fact that the method `Files.string_to_filenames` returns a list of lists of filenames, so that the file methods that assume filenames to be string (as `next_filehandle` here) cannot be called.

Using glob pattern (with '!') does not raise errors, as in that case patterns are stored as a list, not list of lists. Is this behavior of filelists intended?

By the way, my use case for filelists is the following. I am using `udapi` to transform more than 200 conllu files; for each of them I'd like to read the input, apply my blocks, then write a new conllu file named `[original-filename]_MODIFIED.conllu`. I am not sure, but I think the only way to do it is by passing to synced filelists, one to `read.Conllu`, and one to `write.Conllu`, with the output list holding the modified file paths.

Am I missing something?

**Comment by martinpopel** [comment]
Thanks for reporting this bug. I hope I fixed it now.
(Yes, tests and documentation are badly needed in Udapi.)

> I am using udapi to transform more than 200 conllu files;
> ...
> then write a new conllu file named [original-filename]_MODIFIED.conllu

One solution is to use Bash:

```bash
for f in *.conllu; do 
  udapy -s my.Block < $f > ${f%.conllu}_MODIFIED.conllu;
done
```

Another solution within Udapi (using 2c39b236) is:

```
udapy read.Conllu files='!*.conllu' \
  my.Block \
  util.Eval doc='doc.meta["docname"]=doc.meta["loaded_from"][:-7]+"_MODIFIED.conllu"' \
  write.Conllu docname_as_file=1
```

> the only way to do it is by passing to synced filelists, one to read.Conllu, and one to write.Conllu

And this solution should now work as well.

**Comment by francescomambrini** [comment]
Thank you for the fix and the two solutions!
