### ISSUE TITLE
Different behavior of node.parent in Udapi-python CLI and Udapi-python block

### ISSUE THREAD

**Issue by Akshayanti** [udapi/udapi-python#58]
I've been noticing different behavior of some defined attributes (not sure if it's the right term) when they are used in a udapy block vs when they are called from the CLI. I am not sure what is causing this, but this is causing deviations from the intended effect of the written udapy block. Please find an example as below:

Sample Input CONLL-U data (source UDv2.4 af-afribooms train-s795, edited to root at tokenID=1), called dummy.conllu:

```
# sent_id = train-s795
# text = Enigiemand in beheer of in besit van enige eiendom
# org_sent_id = 795
1	Enigiemand	enigiemand	PRON	PO	PronType=Ind	0	root	_	_
2	in	in	ADP	SVS	AdpType=Prep	3	case	_	_
3	beheer	beheer	NOUN	NA	Number=Sing	1	obl	_	_
4	of	of	CCONJ	KN	_	2	cc	_	_
5	in	in	ADP	SVS	AdpType=Prep	6	case	_	_
6	besit	besit	NOUN	NA	Number=Sing	2	obl	_	_
7	van	van	ADP	SVS	AdpType=Prep	9	case	_	_
8	enige	enig	PRON	PO	PronType=Ind	9	amod	_	_
9	eiendom	eiendom	NOUN	NSE	Number=Sing	6	nmod	_	_
```

CLI Command, and output:
```
udapy util.Eval node='if node.upos == "CCONJ" and node.udeprel == "cc": print(node.ord, node.parent.ord, [x.ord for x in node.parent.children], sep="\n")' < dummy.conllu
```

```
4
2
[4, 6]
```

Udapi Block Function, and output:
```
def changeHead_sibling(self, node):
    if node.upos == "CCONJ" and node.udeprel == "cc":
        print(node, node.parent, [x.address() for x in node.parent.children], sep="\n")
```

```
node<train-s795#4, of>
node<train-s795#3, beheer>
['train-s795#2', 'train-s795#4']
```

**Comment by martinpopel** [comment]
Are you sure your block only calls `self.changeHead_sibling(node)` from `process_node` and nothing else? And is the block applied on the unchanged `dummy.conllu`?
I guess your block (or something else in your pipeline) first does `of_node.parent = beheer_node`.

When I run the block myself, it prints
```
node<train-s795#4, of>
node<train-s795#2, in>
['train-s795#4', 'train-s795#6']
```
as expected.

**Comment by Akshayanti** [comment]
Thank you for the quick reply. I found a bug in the pipeline that was handing the non-projective association, and making the change as you mentioned earlier. It was an implementation issue at my end.
